FileVersion = 1
Projects = {sokol-clear = {Path = "sokol-clear"}, sokol-beef = {Path = ".."}}

[Workspace]
StartupProject = "sokol-clear"

[Configs.Test.Win32]
ConfigSelections = {corlib = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {corlib = {Config = "Debug"}}
